snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://redis:6379
            logging: true
    class:
        connection_wrapper: App\ImpRedis\Connection\ImpConnectionWrapper
        logger: App\ImpRedis\Logger\ImpRedisLogger
