version: '3.8'

services:
  db:
    image: mariadb:10.2.29
    ports:
      - "3317:3306"
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
    networks:
      - symfony

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Redirige le port 80 vers le conteneur Nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf  # Fichier de configuration Nginx
      - /home/taneg/Projects/blog:/var/www/html  # Répertoire public de Symfony
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - /home/taneg/Projects/blog:/var/www/html
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  persistent:
